name: Azure Frontend

on:
  workflow_call: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Inject Secrets
        run: |
          sed -i "s|API_URL_PLACEHOLDER|${{ secrets.TESTING_API_URL }}|" src/environments/environment.testing.ts
        working-directory: Frontend

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push to ghcr
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/document-editor-frontend:latest
            ghcr.io/${{ github.repository_owner }}/document-editor-frontend:${{ github.sha }}

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_08E833010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./Frontend"
          output_location: "dist/document-editor/browser"
          app_build_command: "npm ci && npm run build -- --configuration testing"
