name: Verify

on:
  workflow_dispatch:
  push:
    branches:
      - test
      - main
  pull_request:
    branches:
      - main
      - test

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Installing Dependencies
        run: dotnet restore document-editor.sln
        working-directory: Backend

      - name: Format
        run: dotnet format document-editor.sln --verify-no-changes
        working-directory: Backend

      - name: Test
        run: dotnet test document-editor.sln
        working-directory: Backend

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: Backend

  Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Installing Dependencies
        run: npm ci
        working-directory: Frontend

      - name: Linting
        run: npx ng lint
        working-directory: Frontend

      - name: Building
        run: npx ng build
        working-directory: Frontend

  call-backend:
    if: github.event_name == 'push' && github.event.pull_request.base.ref != 'main'
    needs: [ Backend, Frontend ]
    uses: ./.github/workflows/test_backend.yml
    secrets: inherit
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write

  call-frontend:
    if: github.event_name == 'push' && github.event.pull_request.base.ref != 'main'
    needs: [ Backend, Frontend ]
    uses: ./.github/workflows/test_frontend.yml
    secrets: inherit
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write